# Generated by Django 4.0.1 on 2022-02-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworkApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='repassword',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
