# Generated by Django 4.0.1 on 2022-02-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetworkApp', '0002_user_firstname_user_lastname_user_repassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='avatars/guest.png', upload_to='avatars')),
                ('cover_image', models.ImageField(default='avatars/cover.png', upload_to='avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to='SocialNetworkApp.user')),
            ],
        ),
    ]
